### ISSUE TITLE
[LANG] FR

### ISSUE THREAD

**Issue by mech-tools** [ElfFriend-DnD/foundryvtt-auto-roll-npc-save-5e#1]
Hello,

Please find attached the fr.json file for the French language.
[fr.zip](https://github.com/ElfFriend-DnD/foundryvtt-auto-roll-npc-save-5e/files/7866531/fr.zip)

**Comment by mech-tools** [comment]
See https://github.com/ElfFriend-DnD/foundryvtt-attack-roll-check-5e/issues/5#issuecomment-1013958380

**Comment by mech-tools** [comment]
Still there :)

**Comment by mech-tools** [comment]
I mean the PR: https://github.com/ElfFriend-DnD/foundryvtt-auto-roll-npc-save-5e/pull/2

**Comment by akrigline** [comment]
whoops, thanks!
