### ISSUE TITLE
Possible issue with MRE and Advantage/Disadvantage prompt

### ISSUE THREAD

**Issue by fel-pt** [ElfFriend-DnD/foundryvtt-auto-roll-npc-save-5e#3]
I'm not sure if this is working as intended or if it's simply a limitation, but when MRE and Auto Roll NPC Save are both enabled, Foundry won't prompt for Advantage or Disadvantage and will simply do a straight roll.

**Comment by akrigline** [comment]
Just to confirm, what settings are you using for MRE? Can you send me a screenshot?

**Comment by fel-pt** [comment]
The default ones. I think I still haven't change anything. On a sidenote, regarding MRE: aren't the attack and damage rolls supposed to merge with the item card, or did I misunderstand? I haven't been able to get that to work. Thank you :)

![image](https://user-images.githubusercontent.com/79886727/153320393-a5aee386-abd4-4983-945d-f91806e8b1bc.png)

**Comment by akrigline** [comment]
Looks like you have the roll dialog behavior set to skip, so rolling any ability check, skill, or save will automatically skip the prompt (including the ones from this module).

For the whole roll card merging thing, that behavior was scrapped a while ago, I think there's some outdated images around but the MRE repo wiki is up to date

**Comment by fel-pt** [comment]
@akrigline  Sometimes I can be so dense... I hadn't realized that the Roll Dialog Modifier Key would also work to skip the Dialog if the option was set to show! I only figured that out right now because otherwise the option wouldn't really make a lot of sense in MRE.

And honestly, thank you so very much for your modules. They were a godsend now that I'm setting up Foundry again and didn't want to go down the excessive automation rabbit hole again.
